name: phone_repair_service_199
description: 199 Phone Repair Service
publish_to: 'none'
version: 0.3.5

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.3
  connectivity_plus: ^5.0.0
  firebase_analytics: ^10.8.4
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.8
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.19.0
  isar_flutter_libs: ^3.1.0+1
  line_icons: ^2.0.3
  marquee: ^2.2.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.3.4
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ussd_code.json
    - .env
  fonts:
    - family: NotoSansMyanmar
      fonts:
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Black.ttf
          weight: 900
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Bold.ttf       
          weight: 700   
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-ExtraBold.ttf
          weight: 800
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-ExtraLight.ttf
          weight: 200
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Light.ttf
          weight: 300
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Medium.ttf
          weight: 500
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Regular.ttf
          weight: 400
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-SemiBold.ttf
          weight: 600
        - asset: assets/font_family/NotoSansMyanmar/NotoSansMyanmar-Thin.ttf
          weight: 100
    - family: NotoSerifMyanmar
      fonts:
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Black.ttf
          weight: 900
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Bold.ttf
          weight: 700
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-ExtraBold.ttf
          weight: 800
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-ExtraLight.ttf
          weight: 200
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Light.ttf
          weight: 300
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Medium.ttf
          weight: 500
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Regular.ttf
          weight: 400
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-SemiBold.ttf
          weight: 600
        - asset: assets/font_family/NotoSerifMyanmar/NotoSerifMyanmar-Thin.ttf
          weight: 100

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/199SplashLogoNew.png
  android: true
  fullscreen: true