name: phone_repair_service_199
description: 199 Phone Repair Service
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.3
  connectivity_plus: ^5.0.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  go_router: ^11.1.2
  line_icons: ^2.0.3
  marquee: ^2.2.3
  provider: ^6.0.5
  text_scroll: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
