name: phone_repair_service_199
description: 199 Phone Repair Service
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.3
  connectivity_plus: ^5.0.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^16.1.0
  go_router: ^12.0.1
  html: ^0.15.4
  http: ^1.1.0
  line_icons: ^2.0.3
  marquee: ^2.2.3
  provider: ^6.0.5
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^2.3.4
  build_runner: ^2.4.6
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ussd_code.json
