name: phone_repair_service_199
description: 199 Phone Repair Service
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^11.1.2
  line_icons: ^2.0.3
  marquee: ^2.2.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
